Add in retry logic for OpenAI, keep track of in-progress classification
jdrbc/podly_pure_podcasts pull request #28
Opened 2024-11-21 06:27 UTC by ross-w

I've been having some issues on my local setup whereby the OpenAI-compatible API occasionally returns 500 (eg if it's too busy to handle the request.)

The problem being that when this happens, Podly does not retry, and instead creates an empty directory under classifications. This has the effect that when it later tries to process the segments, it gets a FileNotFound error on line 254 and fails. As this has now written to storage, retrying in your podcast app results in the same thing occurring, as it assumes it has already sent that segment off and gets the FileNotFound again

This PR adds:
1) Retry logic to the OpenAI call upon receiving a 500; and
2) Adds extra error handling to the classification process, including an in-progress indicator

Happy for any feedback on this unsolicited PR; not sure if this is how you'd prefer I approached the above. Testing locally for me solves the issue I was having.

2024-11-21 17:41 UTC, frrad requested changes
(I'm pretty sure I can approve this and @jdrbc doesn't have to do it.)

Thanks for your contribution, it looks good to me. I left a few nits and I think CI may fail (you can run a pretty good simulation locally with `./scripts/ci` (bonus points if you add a new README section called "contributing" or similar with this information)) but other than that I think we should merge this.

2024-11-21 17:41 UTC, frrad commented on src/podcast_processor/podcast_processor.py
> +            with open(f"{target_dir}/.in_progress", "w") as f:
nit: I might put this inside the `try`, since this is what we're cleaning up in the `finally` block.

2024-11-21 17:41 UTC, frrad commented on src/podcast_processor/podcast_processor.py
> +                    with open(f"{target_dir}/identification.txt", "w") as f:
nit: maybe factor out a variable `identification_path = f"{target_dir}/identification.txt"`

2024-11-21 17:41 UTC, frrad commented on src/podcast_processor/podcast_processor.py
> +                    with open(f"{target_dir}/identification.txt", "w") as f:
and similarly for some of these other variables. Could do it up on L201 where `target_dir` is defined.

2024-11-22 05:10 UTC, frrad approved these changes
LGTM! I think you should be able to merge. Let me know if not and I can try to do it from my end (you may have to mark as non-draft first)

2024-11-22 05:12 UTC, ross-w commented
Thanks @frrad let me battle test the new changes locally first, then I'll remove draft.

Sorry about the CI retries. I missed the linting errors the first time, then upon fixing them I introduced more.

2024-11-22 05:14 UTC, frrad commented
sounds good 👍

2024-11-22 05:42 UTC, ross-w commented
Seems to work. Merge when ready

2024-11-22 05:44 UTC, merged

2024-11-23 17:59 UTC, jdrbc commented
amazing! thanks :)